decomposer:
  data:
    path: /home/ubuntu/projects/spokenDigits
    type: recordings
    mixing: True

  transforms:
    step_size: 8
    embedding_path: /home/ubuntu/projects/digits/digits/features/models/decomposition/latest.pt
    embedding_hidden: 
      - 256
      - 128
      - 64
      - 32
    embedding_input: 130
  
  training:
    batch_size: 60
    num_workers: 8
    input_dim: 32
    hidden_dim: 256
    output_dim: 32
    learning_rate: 5.e-6
    weight_decay: 1.e-5
    epochs: 200
    drop_out: .5
    model_path: /home/ubuntu/projects/digits/digits/models/decomposition/latest.pt

full_decomposer:
  data:
    path: /home/ubuntu/projects/spokenDigits
    type: recordings
    mixing: True
    full: True

  transforms:
    step_size: 8
    embedding_path: /home/ubuntu/projects/digits/digits/features/models/decomposition/latest.pt
    embedding_hidden: 
      - 256
      - 128
      - 64
      - 32
    embedding_input: 130
  
  training:
    batch_size: 60
    num_workers: 8
    input_dim: 1040
    hidden_dim: 256
    output_dim: 32
    learning_rate: 1.e-6
    weight_decay: 1.e-5
    epochs: 500
    drop_out: .5
    model_path: /home/ubuntu/projects/digits/digits/models/fullDecomposition/latest.pt